---
- name: Fill up TrustedUserCAKeys file
  ansible.builtin.template:
    src: trusted-user-ca-keys.j2
    dest: /etc/ssh/trusted-user-ca-keys.pem
    mode: '644'
  when: ssh_trusted_user_ca_keys is defined

- name: Configure sshd_config file
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '644'
  notify:
    - reload ssh

- name: Check syntax of sshd_config file
  ansible.builtin.command: sshd -t
  register: result
  changed_when: "result.rc != 0"
  failed_when: ('ERROR' in result.stdout)
