---
- ansible.builtin.include_tasks: "{{ role_path }}/tasks/debian/install.yml"
  tags:
    - install_openssh
    - install

- ansible.builtin.include_tasks: "{{ role_path }}/tasks/debian/configure.yml"
  tags:
    - configure_openssh
    - configure
