---
- name: Include ./debian/install.yml
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/debian/install.yml"
  tags:
    - install_openssh
    - install

- name: Include ./debian/configure.yml
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/debian/configure.yml"
  tags:
    - configure_openssh
    - configure
