---
- name: Setup role for Debian system
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: debian.yml
  tags:
    - system
    - debian

- name: Setup role for RedHat system
  when: ansible_os_family == 'RedHat'
  ansible.builtin.include_tasks: redhat.yml
  tags:
    - system
    - redhat
