---
- name: Include ./redhat/install.yml
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/install.yml"
  tags:
    - install_openssh
    - install

- name: Include ./redhat/configure.yml
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/redhat/configure.yml"
  tags:
    - configure_openssh
    - configure
