---
dependency:
  name: galaxy
provisioner:
  name: ansible
verifier:
  name: ansible
driver:
  name: docker
platforms:
  - name: instance-debian
    image: "6nsh/debian${MOLECULE_DISTRO:-11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
