---
  name: Molecule test & Ansible-Galaxy CI
  
  on:
    push:
      branches:
        - main
      paths-ignore:
        - '**/README.md'
    pull_request:
      branches:
        - main
      paths-ignore:
        - '**/README.md'
  
  defaults:
    run:
      working-directory: 'leadlineit.openssh'
  
  jobs:
    lint:
      name: Linting the syntax
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            path: 'leadlineit.openssh'
  
        - name: Set up Python 3
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
      
        - name: Install test dependencies
          run: |
            pip3 install --upgrade pip
            pip3 install ansible-lint \
            yamllint
        
        - name: Lint role code
          run: |
            ansible-lint .
            yamllint .
  
    test_debian:
      name: Molecule tests for Debian
      runs-on: ubuntu-latest
      needs:
        - lint
      strategy:
        matrix:
          distro:
            - '12'
            - '11'
            - '10'
            - '9'
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            path: 'leadlineit.openssh'
  
        - name: Set up Python 3
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
      
        - name: Install dependencies
          run: |
            pip3 install --upgrade pip
            pip3 install ansible \
            molecule-plugins[docker] \
    
        - name: Test with molecule
          run: molecule test --scenario-name debian
          env:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_DISTRO: ${{ matrix.distro }}
  
    test_centos:
      name: Molecule tests for CentOS
      runs-on: ubuntu-latest
      needs:
        - lint
      strategy:
        matrix:
          distro:
            - '-stream9'
            - '-stream8'
            - '7'
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            path: 'leadlineit.openssh'
        
        - name: Set up Python 3
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        
        - name: Install dependencies
          run: |
            pip3 install --upgrade pip
            pip3 install ansible \
            molecule-plugins[docker]
        
        - name: Test with molecule
          run: molecule test --scenario-name centos
          env:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_DISTRO: ${{ matrix.distro }}
  
    release:
      name: Release
      needs:
        - test_debian
        - test_centos
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            path: 'leadlineit.openssh'
  
        - name: Set up Python 3
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
  
        - name: Install Ansible
          run: pip3 install ansible-base
  
        - name: Trigger a new import on Ansible Galaxy
          run: |
            ansible-galaxy import \
            --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} \
            $(echo ${{ github.repository }} | cut -d/ -f1) \
            $(echo ${{ github.repository }} | cut -d- -f3)
