---
name: Molecule test & Ansible-Galaxy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'leadlineit.openssh'

jobs:
  lint:
    name: Linting the syntax
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'leadlineit.openssh'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install yamllint

      - name: Lint code
        run: |
          yamllint .
  test:
    name: Molecule tests
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        distro:
          - buster
          - bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'leadlineit.openssh'
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ansible \
          ansible-lint \
          molecule[docker,lint] \
          flake8 \
          yamllint \
          docker
      - name: Test with molecule
        run: |
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    name: Release
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'leadlineit.openssh'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-base

      - name: Trigger a new import on Ansible Galaxy
        run: |
          ansible-galaxy import \
          --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} \
          $(echo ${{ github.repository }} | cut -d/ -f1) \
          $(echo ${{ github.repository }} | cut -d- -f3)
